version: "3"
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
    tty: true
    volumes:
      - "gql-demo-data:/var/lib/postgresql/data"
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/go/src/repo
    tty: true
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
volumes:
  gql-demo-data:
    external: true
networks:
  default:
    external:
      name: gql-demo-network
